packageExtensions:
  "@vueuse/core@*":
    peerDependencies:
      vue: ^3.0.0
  "@vueuse/shared@*":
    peerDependencies:
      vue: ^3.0.0
  vite-plugin-vuetify@1.0.2:
    peerDependencies:
      vue: ^3.0.0

yarnPath: .yarn/releases/yarn-3.6.1.cjs
