packageExtensions:
  "@vueuse/core@9.13.0":
    peerDependencies:
      vue: ^3.0.0
  "@vueuse/shared@9.13.0":
    peerDependencies:
      vue: ^3.0.0
  vite-plugin-vuetify@1.0.2:
    peerDependencies:
      vue: ^3.0.0

yarnPath: .yarn/releases/yarn-3.5.0.cjs
